version: '3'
services:
  database:
    container_name: postgres_container
    image: 'postgres'
    restart: always
    ports:
      - "${DATABASE_HOST}:${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./srcs/database:/var/lib/postgresql/data
    healthcheck:
     test: ["CMD", "pg_isready",  "-d",  "${DATABASE_NAME}", "-U", "${DATABASE_USER}"]
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=${DATABASE_DATA}
      - NODE_ENV=${NODE_ENV}

  website:
    build: 
      context: srcs/
      dockerfile: Dockerfile
    image: website
    #hostname: 127.0.0.1
    ports:
      - "${FRONT_HOST}:${FRONT_PORT}:${FRONT_PORT}"
    container_name: website_container
    depends_on:
      database:
        condition: service_healthy
    environment:
      PORT: ${BACK_PORT}
      HOST: ${BACK_HOST}
      ADDRESS: ${BACK_HOST}:${BACK_PORT}

      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: ${DATABASE_LINK}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_ADDRESS: ${DATABASE_LINK}:${DATABASE_PORT}

      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      VUE_APP_PORT: ${FRONT_PORT}
      VUE_APP_HOST: ${FRONT_HOST}
      VUE_APP_ADDRESS: ${FRONT_HOST}:${FRONT_PORT}
      VUE_APP_BACK: ${BACK_HOST}:${BACK_PORT}
      VUE_APP_NODE_ENV: ${NODE_ENV}

      API_42_ID: ${API_42_ID}
      API_42_SECRET: ${API_42_SECRET}
      API_GITHUB_ID: ${API_GITHUB_ID}
      API_GITHUB_SECRET: ${API_GITHUB_SECRET}

      NODE_ENV: ${NODE_ENV}

  pgadmin:
    container_name: pgadmin_container
    build:
      context: srcs/pgadmin4
      dockerfile: Dockerfile
      args:
        - JSON_FILE=${PGADMIN_SERVER_JSON_FILE}
    restart: always
    ports:
      - ${PGADMIN_HOST}:${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    links: 
      - "database:${DATABASE_LINK}"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
      - PGADMIN_SERVER_JSON_FILE=${PGADMIN_SERVER_JSON_FILE}

  # backend:
  #   build: 
  #     context: srcs/backend
  #     dockerfile: Dockerfile
  #   image: backend
  #   #hostname: 127.0.0.1
  #   ports:
  #     - "${BACK_HOST}:${BACK_PORT}:${BACK_PORT}"
  #   container_name: backend_container
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   environment:
  #     PORT: ${BACK_PORT}
  #     HOST: ${BACK_HOST}
  #     ADDRESS: ${BACK_HOST}:${BACK_PORT}

  #     FRONT_ADDRESS: ${FRONT_LINK}:${FRONT_PORT}

  #     DATABASE_TYPE: ${DATABASE_TYPE}
  #     DATABASE_HOST: ${DATABASE_LINK}
  #     DATABASE_PORT: ${DATABASE_PORT}
  #     DATABASE_ADDRESS: ${DATABASE_HOST}:${DATABASE_PORT}

  #     NODE_ENV: ${NODE_ENV}

  #     # #THAT MUST BE MOVE INSIDE SECRET
  #     DATABASE_USER: ${DATABASE_USER}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}

  # frontend:
  #   build: 
  #     context: srcs/frontend
  #     dockerfile: Dockerfile
  #   #hostname: 127.0.0.1
  #   image: frontend
  #   ports:
  #     - "${FRONT_PORT}:${FRONT_PORT}"
  #   depends_on:
  #     - backend
  #   container_name: frontend_container
  #   environment: #In VUEJS env variable must start by VUE_APP_*
  #     VUE_APP_PORT: ${FRONT_PORT}
  #     VUE_APP_HOST: ${FRONT_HOST}
  #     VUE_APP_ADDRESS: ${FRONT_HOST}:${FRONT_PORT}
  #     VUE_APP_BACK: ${BACK_LINK}
  #     VUE_APP_NODE_ENV: ${NODE_ENV}

# secrets:
#   database_password:
#     file: ${DATABASE_PASSWORD_FILE}