version: '3'
services:
  database:
    container_name: postgres_container
    image: 'postgres'
    restart: always
    ports:
      - "${DATABASE_HOST}:${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./srcs/database:/var/lib/postgresql/data
    healthcheck:
     test: ["CMD", "pg_isready",  "-d",  "${DATABASE_NAME}", "-U", "${DATABASE_USER}"]
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=${DATABASE_DATA}
      - NODE_ENV=${NODE_ENV}

  website:
    build: 
      context: srcs/srcs/
      dockerfile: Dockerfile
      args:
        - VUE_APP_HOST=${VUE_APP_HOST}
        - VUE_APP_PORT=${VUE_APP_PORT}
    image: website
    #hostname: 127.0.0.1
    ports:
      - "${VUE_APP_HOST}:${VUE_APP_PORT}:${VUE_APP_PORT}"
    container_name: website_container
    depends_on:
      database:
        condition: service_healthy
    environment:
      VUE_APP_PORT: ${VUE_APP_PORT}
      VUE_APP_HOST:  ${VUE_APP_HOST}
      VUE_APP_ADDRESS: ${VUE_APP_ADDRESS}

      SESSION_SECRET: ${SESSION_SECRET}
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: ${DATABASE_LINK}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_ADDRESS: ${DATABASE_LINK}:${DATABASE_PORT}

      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

      API_42_ID: ${API_42_ID}
      API_42_SECRET: ${API_42_SECRET}
      API_GITHUB_ID: ${API_GITHUB_ID}
      API_GITHUB_SECRET: ${API_GITHUB_SECRET}

      NODE_ENV: ${NODE_ENV}

  pgadmin:
    container_name: pgadmin_container
    build:
      context: srcs/pgadmin4
      dockerfile: Dockerfile
      args:
        - JSON_FILE=${PGADMIN_SERVER_JSON_FILE}
    restart: always
    ports:
      - ${PGADMIN_HOST}:${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    links: 
      - "database:${DATABASE_LINK}"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
      - PGADMIN_SERVER_JSON_FILE=${PGADMIN_SERVER_JSON_FILE}